name: Linter
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  build:
    name: Linter
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: justia/ga-phplint-5.5@master
